travis:
  secure:
    BINSTAR_TOKEN: EIUPvtiWZxmV8evhHb21ZMD5g8swNVDNQWcnf4lKNIry93wSNePzRqUjytcCJ63wtlMm8kT2zxd1+YC2DIjO6khiMrhbCrawAMux3pbiS+REDPQjbfH4+5qlG6X3UkOVdb5agZEbZZdY8xmvM9DJ2yXk7Uz+29JIpDNGb4gLFdtrKry1q4Hbsdwht6bAHvmopsfTHpN+TRBB2o0l2oDQZ5O5o7VgBVzr5GC3Q0qHvvcq++CHN7HuoxutfNrkq+o2VbmAy0Je9cDQV3jIa+3fyIypu1/sVrmQUVm3XeVleE9LAldvmBQOs/RQgQOibE6p5vT0vJ9Yeh+zSpzq+nH+rZmJegA8D9mvs2RzrH3hsbyJELM1dK2ybTeJbkz1IJ6nGHSrEREA6p4lYPA2DPwaQYJneY23soRyQbkX9jVn9NONYmXHOVd1lUsWWSRhYSYUsL9WX6gisZr5w6wQ3Bq0M+mNtkin5czvKa8e/3nUWKEXEe3O0/sGc1YwsA0WdllkjvEns8K6abnSqe076JmX9LzyMxDdrfmNTpGZWFi+JHAIpGUUZDuDKwvyOXdov7wwiOPziT4VB99pMNhMVGcWISW7F2bz4mSbw1Y4MsN6z9AjKvgDSlFlb+zfPorL5MPBQPl5XaT9d5dsnru5J+WvRVOxeWK73J2iuNjf21Zx+DY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
