travis:
  secure:
    BINSTAR_TOKEN: HJsBI5VHPOsfg5PBoxD7JmtDbt3bGynse8OHEecqcwGlih9vtnXS+S7LfzHzLirybZjCrhG5hlqlTseV2rGD01xGpa8tNJtl6f5+LGkSis1tEfypBjEKpNKbx/CeXwW2NH2Vf80JpJPUy5Rb8Rj3h9smXJI61NUFTXbvmS6wxEQRFIOzC7UwI264qDHb+eF1agY7SuvBjK+zqjJrK0gsGio+qT9M4oR3klTDu/0GMNnDMsY68aN0dG9vP9FPjK5+5QovCgdpQkXJV41C7F/yx4CsXbLBIHHaFB7dfL5Fs+YEx3fKFPfyd60JxoRKJYISvasrPWbIPVuKB0v0HHNAy8I0/ChOrYrHK8+9WQMcUoEmXIdQmo2fnHFM1tb8wObKfd+vg/PXH/FlmV05v7kWs7n5SMgcwg/64mb5Gc1oEtzz2dfkvKbKB9vVx2NjyjFmRo0KYXUgNRiqa7gP64rLpH5oheAjsGL8EvsCpKSbP7OJytr6Xqd9GbmSY1CAFtWYB2VLuWeu0rwjJ9gLz9X9kVsGBKFaT4GeopdzjobwvCd1BsqN2jDXGO0WSsj17k6p6HgaD9hEBPX6g7W9emw9mBH7Q9EAdyswCZFHqfOWKGPftfdXzhUpqjEgpeA7OmOHcUXMGx7zo6+Wwjd4WAX61+m0yG8LL/h11AHw1rJ82f8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
